[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Regular"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
  { action = "Paste", key = "V", mods = "Control|Shift" },
  { action = "Copy", key = "C", mods = "Control|Shift" },
  { action = "PasteSelection", key = "Insert", mods = "Shift" },
  { action = "ResetFontSize", key = "Key0", mods = "Control" },
  { action = "IncreaseFontSize", key = "Equals", mods = "Control" },
  { action = "IncreaseFontSize", key = "Plus", mods = "Control" },
  { action = "DecreaseFontSize", key = "Minus", mods = "Control" },
  { action = "ToggleFullscreen", key = "F11", mods = "None" },
  { action = "Paste", key = "Paste", mods = "None" },
  { action = "Copy", key = "Copy", mods = "None" },
  { action = "ClearLogNotice", key = "L", mods = "Control" },
  { chars = "\f", key = "L", mods = "Control" },
  { action = "ScrollPageUp", key = "PageUp", mode = "~Alt", mods = "None" },
  { action = "ScrollPageDown", key = "PageDown", mode = "~Alt", mods = "None" },
  { action = "ScrollToTop", key = "Home", mode = "~Alt", mods = "Shift" },
  { action = "ScrollToBottom", key = "End", mode = "~Alt", mods = "Shift" },
]

[scrolling]
history = 100000

[window]
dynamic_padding = true
opacity = 0.97
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new", "-As0"]

# autogenerated by: https://github.com/Gogh-Co/Gogh
[general]
import = [
  "~/.config/theme/alacritty.toml",
  # Optional Catppuccin flavours, kept for reference:
  # "~/.config/catppuccin/alacritty/catppuccin-latte.toml"
  # "~/.config/catppuccin/alacritty/catppuccin-frappe.toml"
  # "~/.config/catppuccin/alacritty/catppuccin-macchiato.toml"
  # "~/.config/catppuccin/alacritty/catppuccin-mocha.toml"
]
