import = [
  # uncomment the flavour you want below:
  # "~/.config/catppuccin/alacritty/catppuccin-latte.toml"
  # "~/.config/catppuccin/alacritty/catppuccin-frappe.toml"
  # "~/.config/catppuccin/alacritty/catppuccin-macchiato.toml"
  # "~/.config/catppuccin/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Regular"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
    { action = "Paste", key = "V", mods = "Control|Shift" },
    { action = "Copy", key = "C", mods = "Control|Shift" },
    { action = "PasteSelection", key = "Insert", mods = "Shift" },
    { action = "ResetFontSize", key = "Key0", mods = "Control" },
    { action = "IncreaseFontSize", key = "Equals", mods = "Control" },
    { action = "IncreaseFontSize", key = "Plus", mods = "Control" },
    { action = "DecreaseFontSize", key = "Minus", mods = "Control" },
    { action = "ToggleFullscreen", key = "F11", mods = "None" },
    { action = "Paste", key = "Paste", mods = "None" },
    { action = "Copy", key = "Copy", mods = "None" },
    { action = "ClearLogNotice", key = "L", mods = "Control" },
    { chars = "\f", key = "L", mods = "Control" },
    { action = "ScrollPageUp", key = "PageUp", mode = "~Alt", mods = "None" },
    { action = "ScrollPageDown", key = "PageDown", mode = "~Alt", mods = "None" },
    { action = "ScrollToTop", key = "Home", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToBottom", key = "End", mode = "~Alt", mods = "Shift" },
]

[scrolling]
history = 5000

[window]
dynamic_padding = true
opacity = 0.97
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0

[shell]
program = "/usr/bin/tmux"
args = ["new", "-As0"]

# autogenerated by: https://github.com/Gogh-Co/Gogh
[colors]
indexed_colors = [
    { index = 16, color = "#f5a97f" },
    { index = 17, color = "#f4dbd6" },
]

[colors.primary]
background = "#282828"
foreground = "#EBDBB2"
dim_foreground = "#8087a2"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "#24273a"
cursor = "#f4dbd6"

[colors.vi_mode_cursor]
text = "#24273a"
cursor = "#b7bdf8"

[colors.search.matches]
foreground = "#24273a"
background = "#a5adcb"

[colors.search.focused_match]
foreground = "#24273a"
background = "#a6da95"

[colors.footer_bar]
foreground = "#24273a"
background = "#a5adcb"

[colors.hints.start]
foreground = "#24273a"
background = "#eed49f"

[colors.hints.end]
foreground = "#24273a"
background = "#a5adcb"

[colors.selection]
text = "#24273a"
background = "#f4dbd6"

[colors.normal]
black = "#282828"
red = "#CC241D"
green = "#98971A"
yellow = "#D79921"
blue = "#458588"
magenta = "#B16286"
cyan = "#689D6A"
white = "#A89984"

[colors.bright]
black = "#928374"
red = "#FB4934"
green = "#B8BB26"
yellow = "#FABD2F"
blue = "#83A598"
magenta = "#D3869B"
cyan = "#8EC07C"
white = "#EBDBB2"

[colors.dim]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"
