#!/bin/bash
# This scripts must be launched from vim src folder.
# Things to check if I got problem:
# https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
# https://raw.githubusercontent.com/aaren/dotvim/master/install
# http://stackoverflow.com/questions/26956933/how-to-make-vim74-compile-with-python


# Install a regular vim compiled against the system python.
install_vim () {
    make distclean
    # Install
    ./configure \ # --prefix=$HOME/.local \
        --with-features=huge \
        --enable-multibyte \
        --enable-gui=auto --enable-cscope \
        --enable-rubyinterp \
        --enable-luainterp --with-luajit \
        # --with-lua-prefix=$HOME/local/lua_packages/torch/install/bin/th \
        --enable-pythoninterp \
        # --with-python-config-dir="`python-config --prefix`/lib/python2.7/config" \
        # CFLAGS="`python-config --includes`" \
        # LDFLAGS="`python-config --ldflags" \
        # LIBS="`python-config --libs`" \
        --prefix=/usr \
        --enable-gtk2-check \
        --enable-gnome-check \
        --enable-fail-if-missing
    make VIMRUNTIMEDIR=/usr/share/vim/vim74
    sudo checkinstall
}

# Install vim compiled against anaconda python.
install_vim_anaconda () {
    make distclean

    PYTHON_CONFIG=$HOME/anaconda/lib/python2.7/config
    # force vim to use this python binary
    # export vi_cv_path_python=$APPDATA/bin/python

    ./configure \ # --prefix=`python-config --prefix`
        --with-features=huge \
        --enable-multibyte \
        --enable-gui=auto --enable-cscope \
        --enable-rubyinterp \
        --enable-luainterp --with-luajit \
        # --with-lua-prefix=$HOME/local/lua_packages/torch/install/bin/th \
        --enable-pythoninterp \
        --with-python-config-dir=$PYTHON_CONFIG \
        # CFLAGS="`python-config --includes`" \
        # LDFLAGS="-L $PYTHON_CONFIG" \
        # LIBS="`python-config --libs`" \
        --prefix=/usr \
        --enable-gtk2-check \
        --enable-gnome-check \
        --enable-fail-if-missing
    make VIMRUNTIMEDIR=/usr/share/vim/vim74
    sudo checkinstall
}

# Install necessary libs
sudo apt-get build-dep vim
if [[ $1 = "conda" ]]; then
    echo "compiling vim against anaconda python"
    install_vim_anaconda
elif [[ $# -eq 0 ]]; then
    echo "compiling vim against system python"
    install_vim
else
    echo "usage (navigate to vim src folder):"
    echo "./install - compile against system python"
    echo "./install conda - compile against anaconda python"
fi
