;;; aam-org-roam-test.el --- Checks for shared Org-roam helpers -*- lexical-binding: t; -*-

(require 'ert)
(require 'aam-org-roam)

(defvar org-roam-ui-mode)
(defvar org-roam-ui-port)


(ert-deftest aam/org-roam-find-forward-link-visits-an-outgoing-target ()
  (let ((source 'source)
        (target 'target)
        (unlinked 'unlinked)
        visited)
    (cl-letf (((symbol-function 'org-roam-node-at-point)
               (lambda (&optional assert)
                 (should assert)
                 source))
              ((symbol-function 'org-roam-node-id)
               (lambda (node) (symbol-name node)))
              ((symbol-function 'org-roam-db-query)
               (lambda (_query id)
                 (should (equal id "source"))
                 '(("target"))))
              ((symbol-function 'org-roam-node-read)
               (lambda (_initial filter _sort require-match prompt)
                 (should require-match)
                 (should (equal prompt "Forward link: "))
                 (should (funcall filter target))
                 (should-not (funcall filter unlinked))
                 target))
              ((symbol-function 'org-roam-node-visit)
               (lambda (node &rest _)
                 (setq visited node))))
      (aam/org-roam-find-forward-link)
      (should (eq visited target)))))

(ert-deftest aam/org-roam-ui-start-skips-an-occupied-port-pair ()
  (let ((org-roam-ui-mode nil)
        (org-roam-ui-port 35901)
        (aam/org-roam-ui-default-port 35901)
        (aam/org-roam-ui-port-search-limit 3)
        (original-require (symbol-function 'require))
        enabled-with)
    (cl-letf (((symbol-function 'require)
               (lambda (feature &optional filename noerror)
                 (if (eq feature 'org-roam-ui)
                     t
                   (funcall original-require feature filename noerror))))
              ((symbol-function 'aam/check-localhost-port)
               (lambda (port) (= port 35901)))
              ((symbol-function 'aam/org-roam-ui--enable-with-ports)
               (lambda (http-port websocket-port)
                 (setq enabled-with (list http-port websocket-port)
                       org-roam-ui-mode t))))
      (should (= 35902 (aam/org-roam-ui-start)))
      (should (equal enabled-with '(35902 35904))))))

(ert-deftest aam/zettel-search-labels-notes-once-across-searches ()
  (cl-letf (((symbol-function 'aam/zettel--call)
             (lambda (tool &rest args)
               (should (equal tool "search"))
               (should (eq (plist-get args :unlinked) t))
               `((results ((path . "notes/a.org") (title . "A, with a comma"))
                          ((path . ,(format "notes/%s.org" (plist-get args :by)))
                           (title . "B")))))))
    (should (equal (aam/zettel--search "q" '("name" "text") :unlinked t)
                   '(("A, with a comma  [notes/a.org]" . "notes/a.org")
                     ("B  [notes/name.org]" . "notes/name.org")
                     ("B  [notes/text.org]" . "notes/text.org"))))))

(ert-deftest aam/zettel-explore-keeps-unpicked-candidates-across-rounds ()
  (let ((label (lambda (p) (cons (format "%s  [%s]" p p) p)))
        searches offered)
    (cl-letf (((symbol-function 'aam/zettel--search)
               (lambda (query bys &rest _)
                 (push (cons query bys) searches)
                 (mapcar label (if (equal bys '("meaning")) '("hit1" "hit2") '("hit2" "hit3")))))
              ((symbol-function 'aam/zettel--neighbours)
               (lambda (_) (mapcar label '("nb1" "hit1" "hit3"))))
              ((symbol-function 'aam/zettel--pick)
               (lambda (_ cands)
                 (push (mapcar #'cdr cands) offered)
                 (and (null (cdr offered)) (list (funcall label "hit1")))))
              ((symbol-function 'find-file-noselect) (lambda (&rest _) (current-buffer)))
              ((symbol-function 'display-buffer) #'ignore)
              ((symbol-function 'org-mode) #'ignore)
              ((symbol-function 'gptel-mode) #'ignore)
              ((symbol-function 'gptel-context-remove-all) #'ignore)
              ((symbol-function 'gptel-add-file) #'ignore)
              ((symbol-function 'gptel-send) #'ignore))
      (save-window-excursion
        (aam/zettel-explore "how do a and b relate?" "a b"))
      (kill-buffer "*zettel-explore*")
      (should (equal (reverse searches)
                     '(("how do a and b relate?" "meaning") ("a b" "name" "text"))))
      (should (equal (reverse offered)
                     '(("hit1" "hit2" "hit3") ("nb1" "hit3" "hit2")))))))

(ert-deftest aam/zettel-findings-collect-both-paths-of-a-pair ()
  (cl-letf (((symbol-function 'aam/zettel--call)
             (lambda (&rest _)
               '((findings ((kind . "no-role") (path . "notes/a.org") (detail . "A"))
                           ((kind . "unlinked-similar") (path . "notes/a.org")
                            (other . "notes/b.org") (detail . "A <-> B")))))))
    (should (equal (aam/zettel--findings :kinds ["review"])
                   '(("no-role" ("notes/a.org") "A")
                     ("unlinked-similar" ("notes/a.org" "notes/b.org") "A <-> B"))))))

;;; aam-org-roam-test.el ends here
