;;; aam-org-roam-test.el --- Checks for shared Org-roam helpers -*- lexical-binding: t; -*-

(require 'ert)
(require 'aam-org-roam)

(defvar org-roam-ui-mode)
(defvar org-roam-ui-port)


(ert-deftest aam/org-roam-find-forward-link-visits-an-outgoing-target ()
  (let ((source 'source)
        (target 'target)
        (unlinked 'unlinked)
        visited)
    (cl-letf (((symbol-function 'org-roam-node-at-point)
               (lambda (&optional assert)
                 (should assert)
                 source))
              ((symbol-function 'org-roam-node-id)
               (lambda (node) (symbol-name node)))
              ((symbol-function 'org-roam-db-query)
               (lambda (_query id)
                 (should (equal id "source"))
                 '(("target"))))
              ((symbol-function 'org-roam-node-read)
               (lambda (_initial filter _sort require-match prompt)
                 (should require-match)
                 (should (equal prompt "Forward link: "))
                 (should (funcall filter target))
                 (should-not (funcall filter unlinked))
                 target))
              ((symbol-function 'org-roam-node-visit)
               (lambda (node &rest _)
                 (setq visited node))))
      (aam/org-roam-find-forward-link)
      (should (eq visited target)))))

(ert-deftest aam/org-roam-ui-start-skips-an-occupied-port-pair ()
  (let ((org-roam-ui-mode nil)
        (org-roam-ui-port 35901)
        (aam/org-roam-ui-default-port 35901)
        (aam/org-roam-ui-port-search-limit 3)
        (original-require (symbol-function 'require))
        enabled-with)
    (cl-letf (((symbol-function 'require)
               (lambda (feature &optional filename noerror)
                 (if (eq feature 'org-roam-ui)
                     t
                   (funcall original-require feature filename noerror))))
              ((symbol-function 'aam/check-localhost-port)
               (lambda (port) (= port 35901)))
              ((symbol-function 'aam/org-roam-ui--enable-with-ports)
               (lambda (http-port websocket-port)
                 (setq enabled-with (list http-port websocket-port)
                       org-roam-ui-mode t))))
      (should (= 35902 (aam/org-roam-ui-start)))
      (should (equal enabled-with '(35902 35904))))))

;;; aam-org-roam-test.el ends here
