;;; aam-org-roam-test.el --- Checks for shared Org-roam helpers -*- lexical-binding: t; -*-

(require 'ert)
(require 'aam-org-roam)

(ert-deftest aam/org-roam-find-forward-link-visits-an-outgoing-target ()
  (let ((source 'source)
        (target 'target)
        (unlinked 'unlinked)
        visited)
    (cl-letf (((symbol-function 'org-roam-node-at-point)
               (lambda (&optional assert)
                 (should assert)
                 source))
              ((symbol-function 'org-roam-node-id)
               (lambda (node) (symbol-name node)))
              ((symbol-function 'org-roam-db-query)
               (lambda (_query id)
                 (should (equal id "source"))
                 '(("target"))))
              ((symbol-function 'org-roam-node-read)
               (lambda (_initial filter _sort require-match prompt)
                 (should require-match)
                 (should (equal prompt "Forward link: "))
                 (should (funcall filter target))
                 (should-not (funcall filter unlinked))
                 target))
              ((symbol-function 'org-roam-node-visit)
               (lambda (node &rest _)
                 (setq visited node))))
      (aam/org-roam-find-forward-link)
      (should (eq visited target)))))

;;; aam-org-roam-test.el ends here
