#!/usr/bin/env bash
# This scripts must be launched from vim src folder.
# Things to check if I got problem:
# https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
# https://raw.githubusercontent.com/aaren/dotvim/master/install
# http://stackoverflow.com/questions/26956933/how-to-make-vim74-compile-with-python

FLAGS="--prefix=/usr"
FLAGS="$FLAGS --with-features=huge --enable-multibyte"
FLAGS="$FLAGS --enable-gui=auto --enable-cscope"
FLAGS="$FLAGS --enable-rubyinterp"
FLAGS="$FLAGS --enable-luainterp --with-luajit"
# FLAGS="$FLAGS --with-lua-prefix=$HOME/local/lua_packages/torch/install/"
FLAGS="$FLAGS --enable-pythoninterp --enable-python3interp"
FLAGS="$FLAGS --enable-gtk2-check --enable-gnome-check --enable-fail-if-missing"

# Install a regular vim compiled against the system python.
install_vim () {
    make distclean
    # Install
    # FLAGS+=CFLAGS="`python-config --includes`"
    # FLAGS+=LDFLAGS="`python-config --ldflags"
    # FLAGS+=LIBS="`python-config --libs`" \
    FLAGS="$FLAGS --with-python3-config-dir="`python3-config --prefix`/lib/python3.4/config""
    FLAGS="$FLAGS --with-python-config-dir="`python-config --prefix`/lib/python2.7/config""
    ./configure $FLAGS
    make VIMRUNTIMEDIR=/usr/share/vim/vim74 -j4
    sudo checkinstall
}

# Install vim compiled against anaconda python.
install_vim_anaconda () {
    make distclean

    PYTHON_CONFIG=$HOME/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/config
    PYTHON3_CONFIG=$HOME/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/config-3.5m
    # force vim to use this python binary
    # export vi_cv_path_python=$APPDATA/bin/python
    FLAGS="$FLAGS --with-python-config-dir=$PYTHON_CONFIG"
    FLAGS="$FLAGS --with-python3-config-dir=$PYTHON3_CONFIG"

    ./configure $FLAGS
    make VIMRUNTIMEDIR=/usr/share/vim/vim74 -j4
    sudo checkinstall
}

# Install necessary libs
sudo apt-get build-dep vim
if [[ $1 = "conda" ]]; then
    echo "compiling vim against anaconda python"
    install_vim_anaconda
elif [[ $# -eq 0 ]]; then
    echo "compiling vim against system python"
    install_vim
else
    echo "usage (navigate to vim src folder):"
    echo "./install - compile against system python"
    echo "./install conda - compile against anaconda python"
fi
