# bash completion for copilot
# Generated by `copilot completion bash`. Do not edit by hand.
___copilot_is_known_path() {
  case "$1" in
  'login') return 0 ;;
  'help') return 0 ;;
  'init') return 0 ;;
  'update') return 0 ;;
  'version') return 0 ;;
  'plugin') return 0 ;;
  'plugin install') return 0 ;;
  'plugin uninstall') return 0 ;;
  'plugin update') return 0 ;;
  'plugin list') return 0 ;;
  'plugin marketplace') return 0 ;;
  'plugin marketplace add') return 0 ;;
  'plugin marketplace remove') return 0 ;;
  'plugin marketplace list') return 0 ;;
  'plugin marketplace browse') return 0 ;;
  'plugin marketplace update') return 0 ;;
  'mcp') return 0 ;;
  'mcp list') return 0 ;;
  'mcp get') return 0 ;;
  'mcp add') return 0 ;;
  'mcp remove') return 0 ;;
  'plugins') return 0 ;;
  'plugins list') return 0 ;;
  'plugins enable') return 0 ;;
  'plugins disable') return 0 ;;
  'plugins remove') return 0 ;;
  'plugins rm') return 0 ;;
  'plugins install') return 0 ;;
  'plugins add') return 0 ;;
  'plugins update') return 0 ;;
  'plugins marketplace') return 0 ;;
  'plugins marketplace list') return 0 ;;
  'plugins marketplace ls') return 0 ;;
  'plugins marketplace add') return 0 ;;
  'plugins marketplace remove') return 0 ;;
  'plugins marketplace rm') return 0 ;;
  'plugins marketplace browse') return 0 ;;
  'plugins marketplace update') return 0 ;;
  'plugins marketplace refresh') return 0 ;;
  'plugins marketplaces') return 0 ;;
  'plugins marketplaces list') return 0 ;;
  'plugins marketplaces ls') return 0 ;;
  'plugins marketplaces add') return 0 ;;
  'plugins marketplaces remove') return 0 ;;
  'plugins marketplaces rm') return 0 ;;
  'plugins marketplaces browse') return 0 ;;
  'plugins marketplaces update') return 0 ;;
  'plugins marketplaces refresh') return 0 ;;
  'skill') return 0 ;;
  'skill list') return 0 ;;
  'skill add') return 0 ;;
  'skill remove') return 0 ;;
  'completion') return 0 ;;
  *) return 1 ;;
  esac
}

_copilot() {
  local cur prev cword words
  if declare -F _get_comp_words_by_ref >/dev/null 2>&1; then
    _get_comp_words_by_ref -n =: cur prev cword words
  else
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"
    cword=$COMP_CWORD
    words=("${COMP_WORDS[@]}")
  fi

  local ___copilot_required='--add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --attachment --context --disable-mcp-server --effort --env --extension-sdk-path --header --host --interactive --kind --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --name --output-format --plugin-dir --prompt --reasoning-effort --scope --session-id --stream --timeout --tools --transport -C -i -n -p'
  local ___copilot_optional='--bash-env --connect --mouse --resume --share -r'
  local ___copilot_variadic='--allow-tool --allow-url --available-tools --deny-tool --deny-url --excluded-tools --secret-env-vars'

  # Walk words[1..cword-1] to detect the current subcommand path. At the
  # `--` end-of-options marker, count any trailing positionals then stop.
  # Value-taking flags consume tokens differently:
  #   required (`--foo <v>`):   always consume next token as value
  #   optional (`--foo [v]`):   consume next only if it isn't a flag or a
  #                            known subcommand at the current path
  #   variadic (`--foo [v...]`): keep consuming under the same rule
  local __path="" __i=1 __mode=none __argidx=0
  while [ $__i -lt $cword ]; do
    local __w="${words[$__i]}"
    if [ "$__w" = "--" ]; then
      # End-of-options: every following token is a positional operand.
      # Count the completed ones (up to the word being completed) so an
      # already-filled positional slot isn't re-offered.
      __i=$((__i + 1))
      while [ $__i -lt $cword ]; do
        __argidx=$((__argidx + 1))
        __i=$((__i + 1))
      done
      break
    fi

    if [ "$__mode" = "required" ]; then
      __mode=none
      __i=$((__i + 1))
      continue
    fi

    if [ "$__mode" = "optional" ] || [ "$__mode" = "variadic" ]; then
      local __candidate
      if [ -n "$__path" ]; then
        __candidate="$__path $__w"
      else
        __candidate="$__w"
      fi
      if [ "${__w#-}" != "$__w" ] || ___copilot_is_known_path "$__candidate"; then
        # Not a value — stop consuming and reprocess this token.
        __mode=none
      else
        # Consume as value. Optional clears the mode after one token.
        if [ "$__mode" = "optional" ]; then __mode=none; fi
        __i=$((__i + 1))
        continue
      fi
    fi

    if [ "${__w#--*=}" != "$__w" ]; then
      : # --flag=value form, no extra skip
    elif [ "${__w#-}" != "$__w" ]; then
      case " $___copilot_required " in *" $__w "*) __mode=required ;; esac
      case " $___copilot_optional " in *" $__w "*) __mode=optional ;; esac
      case " $___copilot_variadic " in *" $__w "*) __mode=variadic ;; esac
    else
      local __candidate2
      if [ -n "$__path" ]; then
        __candidate2="$__path $__w"
      else
        __candidate2="$__w"
      fi
      if ___copilot_is_known_path "$__candidate2"; then
        __path="$__candidate2"
        __argidx=0
      else
        # A plain word that isn't a subcommand is a positional value;
        # advance the positional index for the resolved path.
        __argidx=$((__argidx + 1))
      fi
    fi
    __i=$((__i + 1))
  done

  # If the previous token is a value-taking flag with declared choices,
  # suggest those choices.
  case "$prev" in
  --model)
    COMPREPLY=($(compgen -W 'auto claude-sonnet-5 claude-fable-5 claude-opus-5 claude-opus-4.8 claude-opus-4.8-fast claude-opus-4.7 claude-sonnet-4.6 claude-opus-4.6 claude-sonnet-4.5 claude-opus-4.5 claude-haiku-4.5 gpt-5.6-sol gpt-5.6-terra gpt-5.6-luna gpt-5.5 gpt-5.4 gpt-5.4-mini gpt-5.3-codex gpt-5-mini mai-code-1-flash-picker gemini-3.7-flash gemini-3.6-flash gemini-3.5-flash gemini-3.1-pro-preview grok-4.5 kimi-k3 kimi-k2.7-code' -- "$cur"))
    return 0
    ;;
  --effort | --reasoning-effort)
    COMPREPLY=($(compgen -W 'none minimal low medium high xhigh max' -- "$cur"))
    return 0
    ;;
  --context)
    COMPREPLY=($(compgen -W 'default long_context' -- "$cur"))
    return 0
    ;;
  --log-level)
    COMPREPLY=($(compgen -W 'none error warning info debug all default' -- "$cur"))
    return 0
    ;;
  --stream)
    COMPREPLY=($(compgen -W 'on off' -- "$cur"))
    return 0
    ;;
  --output-format)
    COMPREPLY=($(compgen -W 'text json' -- "$cur"))
    return 0
    ;;
  --mode)
    COMPREPLY=($(compgen -W 'interactive plan autopilot' -- "$cur"))
    return 0
    ;;
  --transport)
    COMPREPLY=($(compgen -W 'stdio http sse' -- "$cur"))
    return 0
    ;;
  esac

  # A value-taking flag WITHOUT declared choices sits at its value position,
  # not a subcommand/flag slot. Emit no candidates so `complete -o default`
  # falls back to filename completion (correct for path flags like --add-dir,
  # harmless otherwise) -- matching the fish generator. `__mode` is non-none
  # here only for such flags (choice flags already returned above). A required
  # flag's value is mandatory, so route to filenames even when the current word
  # starts with a dash (`--prompt --<Tab>`); for optional/variadic flags the
  # `cur` guard preserves flag completion (e.g. `--resume --<flag>`).
  if [ "$__mode" = "required" ] || { [ "$__mode" != "none" ] && [ "${cur#-}" = "$cur" ]; }; then
    COMPREPLY=()
    return 0
  fi

  # Look up valid flags and subcommands for the resolved path.
  local ___copilot_flags="" ___copilot_subs="" ___copilot_argchoices=""
  case "$__path" in
  '')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs='completion help init login mcp plugin plugins skill update version'
    ;;
  'login')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --device-code --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --host --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --web-flow --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'help')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'init')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'update')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'version')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs='install list marketplace uninstall update'
    ;;
  'plugin install')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin uninstall')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin update')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --all --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin list')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin marketplace')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs='add browse list remove update'
    ;;
  'plugin marketplace add')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin marketplace remove')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --force --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -f -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin marketplace list')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin marketplace browse')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugin marketplace update')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'mcp')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs='add get list remove'
    ;;
  'mcp list')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'mcp get')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --show-secrets --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'mcp add')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --env --excluded-tools --experimental --extension-sdk-path --header --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --show-secrets --silent --stream --timeout --tools --transport --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'mcp remove')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs='add disable enable install list marketplace marketplaces remove rm update'
    ;;
  'plugins list')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --kind --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --scope --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins enable')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mcp --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --skill --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins disable')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mcp --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --skill --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins remove')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mcp --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --skill --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins rm')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mcp --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --skill --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins install')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mcp --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --scope --screen-reader --secret-env-vars --session-id --share --share-gist --silent --skill --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins add')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mcp --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --scope --screen-reader --secret-env-vars --session-id --share --share-gist --silent --skill --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins update')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --all --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplace')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs='add browse list ls refresh remove rm update'
    ;;
  'plugins marketplace list')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplace ls')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplace add')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplace remove')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --force --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplace rm')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --force --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplace browse')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplace update')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplace refresh')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplaces')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs='add browse list ls refresh remove rm update'
    ;;
  'plugins marketplaces list')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplaces ls')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplaces add')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplaces remove')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --force --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplaces rm')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --force --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplaces browse')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplaces update')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'plugins marketplaces refresh')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'skill')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs='add list remove'
    ;;
  'skill list')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --json --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'skill add')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --project --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'skill remove')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  'completion')
    ___copilot_flags='--acp --add-dir --add-github-mcp-tool --add-github-mcp-toolset --additional-mcp-config --agent --allow-all --allow-all-mcp-server-instructions --allow-all-paths --allow-all-tools --allow-all-urls --allow-tool --allow-url --attachment --autopilot --available-tools --banner --bash-env --connect --context --continue --deny-tool --deny-url --disable-builtin-mcps --disable-mcp-server --disallow-temp-dir --effort --enable-all-github-mcp-tools --enable-memory --enable-reasoning-summaries --excluded-tools --experimental --extension-sdk-path --interactive --log-dir --log-level --max-ai-credits --max-autopilot-continues --mode --model --mouse --name --no-ask-user --no-auto-update --no-bash-env --no-color --no-custom-instructions --no-experimental --no-mouse --no-remote --no-remote-export --output-format --plain-diff --plan --plugin-dir --prompt --reasoning-effort --remote --remote-export --resume --screen-reader --secret-env-vars --session-id --share --share-gist --silent --stream --version --yolo -C -i -n -p -r -s -v'
    ___copilot_subs=''
    ;;
  esac

  # A positional argument declared with .choices() suggests those values at
  # its slot. Keyed by "<path>|<argindex>" so choices fire only at the exact
  # positional position (`copilot completion <Tab>`), never at the next token.
  case "$__path|$__argidx" in
  'update|0')
    ___copilot_argchoices='stable prerelease'
    ;;
  'completion|0')
    ___copilot_argchoices='bash zsh fish'
    ;;
  esac

  if [ "${cur#-}" != "$cur" ]; then
    COMPREPLY=($(compgen -W "$___copilot_flags" -- "$cur"))
  else
    COMPREPLY=($(compgen -W "$___copilot_subs $___copilot_argchoices" -- "$cur"))
  fi
  return 0
}

complete -o default -F _copilot copilot
