# Hyprland Configuration
# https://wiki.hypr.land/Configuring/
source = ./dms/execs.conf
source = ./dms/input.conf
source = ./dms/colors.conf
source = ./dms/layout.conf
source = ./dms/decoration.conf
source = ./dms/animations.conf
source = ./dms/rules.conf
source = ./dms/binds.conf
source = ./dms/outputs.conf
source = ./dms/misc.conf
