modmap:
  - name: Default
    application:
      not:
        - Microsoft-edge
        - Google-chrome
    remap:
      CapsLock: Esc
      Esc: CapsLock
keymap:
  - name: Popup Terminal
    remap:
      F12:
        launch: ["bash", "-c", "~/dotfiles/scripts/popup_terminal.sh"]
