;;; autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "config-ai" "config-ai.el" (0 0 0 0))
;;; Generated autoloads from config-ai.el

(autoload 'my-ai-setup "config-ai")

;;;***

;;;### (autoloads nil "config-bibtex" "config-bibtex.el" (0 0 0 0))
;;; Generated autoloads from config-bibtex.el

(autoload 'my-bibtex-setup "config-bibtex")

(register-definition-prefixes "config-bibtex" '("aam/bibtex-generate-autokey"))

;;;***

;;;### (autoloads nil "config-common" "config-common.el" (0 0 0 0))
;;; Generated autoloads from config-common.el

(autoload 'my-common-setup "config-common")

;;;***

;;;### (autoloads nil "config-mail" "config-mail.el" (0 0 0 0))
;;; Generated autoloads from config-mail.el

(autoload 'my-mail-setup "config-mail")

;;;***

;;;### (autoloads nil "config-org" "config-org.el" (0 0 0 0))
;;; Generated autoloads from config-org.el

(autoload 'my-org-setup "config-org")

;;;***

;;;### (autoloads nil "config-python" "config-python.el" (0 0 0 0))
;;; Generated autoloads from config-python.el

(autoload 'my-python-setup "config-python")

;;;***

;;;### (autoloads nil "config-secure" "config-secure.el" (0 0
;;;;;;  0 0))
;;; Generated autoloads from config-secure.el

(autoload 'my-secure-setup "config-secure")

;;;***

;;;### (autoloads nil "config-tex" "config-tex.el" (0 0 0 0))
;;; Generated autoloads from config-tex.el

(autoload 'my-tex-setup "config-tex")

;;;***

;;;### (autoloads nil "config-twitter" "config-twitter.el" (0 0 0
;;;;;;  0))
;;; Generated autoloads from config-twitter.el

(autoload 'my-twitter-setup "config-twitter")

;;;***

;;;### (autoloads nil "config-xwidget" "config-xwidget.el" (0 0 0
;;;;;;  0))
;;; Generated autoloads from config-xwidget.el

(autoload 'my-xwidget-setup "config-xwidget")

;;;***

;;; End of scraped data

(provide 'autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; autoloads.el ends here
