#!/usr/bin/env python3
"""Generate application theme adapters from a canonical palette.toml.

Usage:
    themes/generate.py themes/gruvbox-dark/palette.toml
    themes/generate.py palette.toml --output-dir /tmp/generated-theme
    themes/generate.py palette.toml --check

The input schema is intentionally small and application-neutral. See
themes/gruvbox-dark/palette.toml for an example.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path


ANSI_NAMES = ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")
HEX_COLOR = re.compile(r"^#[0-9a-fA-F]{6}$")
REPO_ROOT = Path(__file__).resolve().parent.parent

# Structural neutrals from the extended Gruvbox grey ramp. These sit between
# background/foreground/selection and aren't semantic accents, so they're not
# part of palette.toml's schema — kept here as fixed constants instead.
NEUTRAL = {
    "bg3": "#665c54",
    "bg4": "#7c6f64",
    "fg3": "#bdae93",
}

# Icon and cursor themes are user choices, not palette colors, but GTK's
# settings.ini and dconf both have to name them and disagreeing copies are how
# the theme drifted last time. Single source of truth, edited by hand.
ICON_THEME = "elementary"
CURSOR_THEME = "sweet-cursors"


def fail(message: str) -> "NoReturn":
    raise ValueError(message)


def color(value: object, label: str) -> str:
    if not isinstance(value, str) or not HEX_COLOR.fullmatch(value):
        fail(f"{label} must be a #RRGGBB color, got {value!r}")
    return value.lower()


def load_palette(path: Path) -> dict[str, object]:
    try:
        data = tomllib.loads(path.read_text())
    except (OSError, tomllib.TOMLDecodeError) as exc:
        fail(f"cannot read {path}: {exc}")

    required = (
        "background",
        "foreground",
        "selection_background",
        "selection_foreground",
        "cursor",
        "cursor_text",
    )
    for key in required:
        color(data.get(key), key)

    ansi = data.get("ansi")
    if not isinstance(ansi, dict):
        fail("ansi must be a table with normal and bright tables")
    for intensity in ("normal", "bright"):
        table = ansi.get(intensity)
        if not isinstance(table, dict):
            fail(f"ansi.{intensity} must be a table")
        for name in ANSI_NAMES:
            color(table.get(name), f"ansi.{intensity}.{name}")

    data["name"] = str(data.get("name", path.stem))
    return data


def get(palette: dict[str, object], key: str) -> str:
    return color(palette[key], key)


def ansi(palette: dict[str, object], intensity: str, name: str) -> str:
    table = palette["ansi"][intensity]
    return color(table[name], f"ansi.{intensity}.{name}")


def all_ansi(palette: dict[str, object]) -> list[str]:
    return [
        ansi(palette, intensity, name)
        for intensity in ("normal", "bright")
        for name in ANSI_NAMES
    ]


def render_kitty(p: dict[str, object]) -> str:
    def line(key: str, value: str) -> str:
        return f"{key:<24}{value}"

    lines = [
        f"## name: {p['name']}",
        "",
        line("selection_foreground", get(p, "selection_foreground")),
        line("selection_background", get(p, "selection_background")),
        "",
        line("background", get(p, "background")),
        line("foreground", get(p, "foreground")),
        "",
    ]
    lines += [line(f"color{i}", value) for i, value in enumerate(all_ansi(p))]
    lines += [
        "",
        line("cursor", get(p, "cursor")),
        line("cursor_text_color", get(p, "cursor_text")),
        "",
        line("url_color", ansi(p, "normal", "blue")),
        "",
        "# START_AUTOGENERATED_TAB_STYLE",
        "# Feel free to update these colors manually and remove these comments.",
        line("active_tab_foreground", get(p, "selection_foreground")),
        line("active_tab_background", get(p, "selection_background")),
        line("inactive_tab_foreground", get(p, "foreground")),
        line("inactive_tab_background", get(p, "background")),
        "# END_AUTOGENERATED_TAB_STYLE",
    ]
    return "\n".join(lines) + "\n"


def render_ghostty(p: dict[str, object]) -> str:
    lines = ["# Generated from palette.toml; Ghostty theme adapter."]
    lines += [f"palette = {i}={value}" for i, value in enumerate(all_ansi(p))]
    lines += [
        f"background = {get(p, 'background')}",
        f"foreground = {get(p, 'foreground')}",
        f"cursor-color = {get(p, 'cursor')}",
        f"cursor-text = {get(p, 'cursor_text')}",
        f"selection-background = {get(p, 'selection_background')}",
        f"selection-foreground = {get(p, 'selection_foreground')}",
    ]
    return "\n".join(lines) + "\n"


def render_alacritty(p: dict[str, object]) -> str:
    def section(name: str, values: dict[str, str]) -> list[str]:
        return [f"[colors.{name}]"] + [
            f'{key} = "{value}"' for key, value in values.items()
        ]

    lines = ["# Generated from palette.toml; Alacritty color adapter."]
    lines += section(
        "primary",
        {"background": get(p, "background"), "foreground": get(p, "foreground")},
    )
    lines += [""] + section(
        "cursor", {"text": get(p, "cursor_text"), "cursor": get(p, "cursor")}
    )
    lines += [""] + section(
        "selection",
        {
            "text": get(p, "selection_foreground"),
            "background": get(p, "selection_background"),
        },
    )
    for intensity in ("normal", "bright"):
        lines += [""] + section(
            intensity, {name: ansi(p, intensity, name) for name in ANSI_NAMES}
        )
    return "\n".join(lines) + "\n"


def render_btop(p: dict[str, object]) -> str:
    normal = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    bright = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    values = {
        "main_bg": get(p, "background"),
        "main_fg": get(p, "foreground"),
        "title": get(p, "foreground"),
        "hi_fg": bright["yellow"],
        "selected_bg": get(p, "selection_background"),
        "selected_fg": get(p, "selection_foreground"),
        "inactive_fg": bright["black"],
        "graph_text": normal["white"],
        "proc_misc": bright["green"],
        "cpu_box": normal["blue"],
        "mem_box": normal["cyan"],
        "net_box": normal["magenta"],
        "proc_box": normal["yellow"],
        "div_line": bright["black"],
        "temp_start": normal["blue"],
        "temp_mid": normal["yellow"],
        "temp_end": bright["red"],
        "cpu_start": normal["green"],
        "cpu_mid": normal["yellow"],
        "cpu_end": bright["red"],
        "free_start": normal["cyan"],
        "free_mid": bright["cyan"],
        "free_end": bright["green"],
        "cached_start": normal["blue"],
        "cached_mid": normal["cyan"],
        "cached_end": bright["blue"],
        "available_start": normal["yellow"],
        "available_mid": bright["yellow"],
        "available_end": bright["white"],
        "used_start": normal["red"],
        "used_mid": bright["red"],
        "used_end": bright["magenta"],
        "download_start": normal["blue"],
        "download_mid": normal["cyan"],
        "download_end": bright["blue"],
        "upload_start": normal["magenta"],
        "upload_mid": bright["magenta"],
        "upload_end": bright["red"],
    }
    return (
        "# Generated from palette.toml; btop adapter.\n"
        + "\n".join(f'theme[{key}]="{value}"' for key, value in values.items())
        + "\n"
    )


def render_noctalia(p: dict[str, object]) -> str:
    normal = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    bright = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    dark = {
        "mPrimary": get(p, "selection_background"),
        "mOnPrimary": get(p, "background"),
        "mSecondary": bright["blue"],
        "mOnSecondary": get(p, "background"),
        "mTertiary": bright["cyan"],
        "mOnTertiary": get(p, "background"),
        "mError": bright["red"],
        "mOnError": get(p, "background"),
        "mSurface": get(p, "background"),
        "mOnSurface": get(p, "foreground"),
        "mSurfaceVariant": normal["black"],
        "mOnSurfaceVariant": normal["white"],
        "mOutline": bright["black"],
        "mShadow": get(p, "background"),
        "mHover": normal["black"],
        "mOnHover": get(p, "foreground"),
        "terminal": {
            "background": get(p, "background"),
            "foreground": get(p, "foreground"),
            "cursor": get(p, "cursor"),
            "cursorText": get(p, "cursor_text"),
            "selectionBg": get(p, "selection_background"),
            "selectionFg": get(p, "selection_foreground"),
            "normal": normal,
            "bright": bright,
        },
    }
    return json.dumps({"dark": dark}, indent=2) + "\n"


def render_dms(p: dict[str, object]) -> str:
    normal = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    bright = {name: ansi(p, "bright", name) for name in ANSI_NAMES}

    def scheme(name: str, light: bool = False) -> dict[str, str]:
        return {
            "name": name,
            "primary": get(p, "selection_background"),
            "primaryText": get(p, "background"),
            "primaryContainer": get(p, "selection_background"),
            "secondary": bright["blue"],
            "surface": get(p, "background"),
            "surfaceText": get(p, "foreground"),
            "surfaceVariant": normal["black"],
            "surfaceVariantText": normal["white"],
            "surfaceTint": get(p, "selection_background"),
            "background": get(p, "background"),
            "backgroundText": get(p, "foreground"),
            "outline": bright["black"],
            "surfaceContainer": get(p, "background"),
            "surfaceContainerHigh": normal["black"],
            "surfaceContainerHighest": normal["black"],
            "error": bright["red"] if not light else normal["red"],
            "warning": bright["yellow"] if not light else normal["yellow"],
            "info": bright["blue"] if not light else normal["blue"],
            "matugen_type": "scheme-expressive",
        }

    return (
        json.dumps(
            {
                "dark": scheme(str(p["name"])),
                "light": scheme(f"{p['name']} (light fallback)", light=True),
            },
            indent=2,
        )
        + "\n"
    )


def mix(hex_a: str, hex_b: str, weight: float) -> str:
    """Blend hex_a toward hex_b; weight 0.0 keeps a, 1.0 returns b."""
    channels = (
        round(
            int(hex_a[i : i + 2], 16) * (1 - weight)
            + int(hex_b[i : i + 2], 16) * weight
        )
        for i in (1, 3, 5)
    )
    return "#" + "".join(f"{c:02x}" for c in channels)


def is_dark(p: dict[str, object]) -> bool:
    return relative_luminance(get(p, "background")) < 0.5


def gtk_colors(p: dict[str, object]) -> dict[str, str]:
    """Map the palette onto libadwaita's color names.

    These names are the whole contract: adw-gtk3 (GTK3) and libadwaita (GTK4)
    both resolve nearly every widget color through them — adw-gtk3-dark's own
    stylesheet references them ~1200 times against only ~130 literal hex
    values. Stock Adwaita is the opposite (788 literal hex, one reference), so
    a palette can only reach GTK3 widgets when adw-gtk3 is the active theme.
    """
    bg = get(p, "background")
    fg = get(p, "foreground")
    accent = get(p, "selection_background")
    accent_fg = get(p, "selection_foreground")
    surface = ansi(p, "normal", "black")  # bg1: chrome one step off the window
    border = ansi(p, "bright", "black")
    dim = ansi(p, "normal", "white")
    red = ansi(p, "bright", "red")
    green = ansi(p, "bright", "green")
    yellow = ansi(p, "bright", "yellow")
    shade = "rgba(0, 0, 0, 0.36)" if is_dark(p) else "rgba(0, 0, 0, 0.12)"

    return {
        # Window and content surfaces.
        "window_bg_color": bg,
        "window_fg_color": fg,
        "view_bg_color": bg,
        "view_fg_color": fg,
        "headerbar_bg_color": surface,
        "headerbar_fg_color": fg,
        "headerbar_backdrop_color": bg,
        "headerbar_border_color": border,
        "sidebar_bg_color": surface,
        "sidebar_fg_color": fg,
        "sidebar_backdrop_color": bg,
        "sidebar_border_color": border,
        "secondary_sidebar_bg_color": mix(bg, surface, 0.5),
        "secondary_sidebar_fg_color": fg,
        "secondary_sidebar_border_color": border,
        "card_bg_color": surface,
        "card_fg_color": fg,
        "dialog_bg_color": surface,
        "dialog_fg_color": fg,
        "popover_bg_color": surface,
        "popover_fg_color": fg,
        "thumbnail_bg_color": surface,
        "thumbnail_fg_color": fg,
        "shade_color": shade,
        "card_shade_color": shade,
        "headerbar_shade_color": shade,
        "sidebar_shade_color": shade,
        "popover_shade_color": shade,
        "scrollbar_outline_color": bg,
        # Semantic accents.
        "accent_bg_color": accent,
        "accent_fg_color": accent_fg,
        "accent_color": accent,
        "destructive_bg_color": red,
        "destructive_fg_color": bg,
        "destructive_color": red,
        "error_bg_color": red,
        "error_fg_color": bg,
        "error_color": red,
        "warning_bg_color": yellow,
        "warning_fg_color": bg,
        "warning_color": yellow,
        "success_bg_color": green,
        "success_fg_color": bg,
        "success_color": green,
        # GTK3 legacy names. adw-gtk3 aliases these to the roles above, but
        # apps that ship their own CSS (and stock Adwaita's few references)
        # still read them directly, so they are defined rather than derived.
        "theme_bg_color": bg,
        "theme_fg_color": fg,
        "theme_base_color": bg,
        "theme_text_color": fg,
        "theme_selected_bg_color": accent,
        "theme_selected_fg_color": accent_fg,
        "theme_unfocused_bg_color": bg,
        "theme_unfocused_fg_color": mix(fg, bg, 0.4),
        "theme_unfocused_base_color": bg,
        "theme_unfocused_text_color": mix(fg, bg, 0.4),
        "theme_unfocused_selected_bg_color": mix(accent, bg, 0.4),
        "theme_unfocused_selected_fg_color": accent_fg,
        "insensitive_bg_color": surface,
        "insensitive_base_color": bg,
        "insensitive_fg_color": dim,
        "unfocused_insensitive_color": dim,
        "text_view_bg": bg,
        "content_view_bg": bg,
        "borders": border,
        "unfocused_borders": mix(border, bg, 0.4),
    }


def gtk_palette_scale(p: dict[str, object]) -> dict[str, str]:
    """GNOME's named palette (blue_1..blue_5, ...), remapped to the theme.

    Adwaita apps hardcode these for status chips, tags and syntax accents, so
    leaving them at GNOME's defaults is what makes an otherwise-themed app
    sprout stock GNOME blue. Each hue is a five-step ramp built from the
    palette's normal/bright pair; orange and brown are blended from red and
    yellow because the ANSI schema has no slot for them.
    """
    bg = get(p, "background")
    fg = get(p, "foreground")
    hues = {
        name: (ansi(p, "normal", name), ansi(p, "bright", name)) for name in ANSI_NAMES
    }
    orange = (
        mix(hues["red"][0], hues["yellow"][0], 0.5),
        mix(hues["red"][1], hues["yellow"][1], 0.5),
    )
    ramps = {
        "blue": hues["blue"],
        "green": hues["green"],
        "yellow": hues["yellow"],
        "red": hues["red"],
        "purple": hues["magenta"],
        "orange": orange,
        "brown": (mix(orange[0], bg, 0.35), mix(orange[1], bg, 0.2)),
    }

    scale: dict[str, str] = {}
    for name, (normal, bright) in ramps.items():
        steps = (
            mix(bright, fg, 0.35),
            bright,
            mix(bright, normal, 0.5),
            normal,
            mix(normal, bg, 0.35),
        )
        for index, value in enumerate(steps, start=1):
            scale[f"{name}_{index}"] = value

    # Neutral ramps: light_1 is the lightest step, dark_5 the darkest.
    light = (
        ansi(p, "bright", "white"),
        fg,
        NEUTRAL["fg3"],
        ansi(p, "normal", "white"),
        NEUTRAL["bg4"],
    )
    dark = (
        ansi(p, "bright", "black"),
        NEUTRAL["bg4"],
        NEUTRAL["bg3"],
        ansi(p, "normal", "black"),
        bg,
    )
    for index, value in enumerate(light, start=1):
        scale[f"light_{index}"] = value
    for index, value in enumerate(dark, start=1):
        scale[f"dark_{index}"] = value
    return scale


# libadwaita 1.6 deprecated @define-color in favour of CSS custom properties
# and reads these from :root. GTK3 has no equivalent, so the GTK4 adapter
# emits both spellings.
GTK4_VARIABLES = (
    "window_bg_color",
    "window_fg_color",
    "view_bg_color",
    "view_fg_color",
    "headerbar_bg_color",
    "headerbar_fg_color",
    "headerbar_backdrop_color",
    "headerbar_border_color",
    "headerbar_shade_color",
    "sidebar_bg_color",
    "sidebar_fg_color",
    "sidebar_backdrop_color",
    "sidebar_border_color",
    "sidebar_shade_color",
    "secondary_sidebar_bg_color",
    "secondary_sidebar_fg_color",
    "secondary_sidebar_border_color",
    "card_bg_color",
    "card_fg_color",
    "card_shade_color",
    "dialog_bg_color",
    "dialog_fg_color",
    "popover_bg_color",
    "popover_fg_color",
    "popover_shade_color",
    "thumbnail_bg_color",
    "thumbnail_fg_color",
    "shade_color",
    "scrollbar_outline_color",
    "accent_bg_color",
    "accent_fg_color",
    "accent_color",
    "destructive_bg_color",
    "destructive_fg_color",
    "destructive_color",
    "error_bg_color",
    "error_fg_color",
    "error_color",
    "warning_bg_color",
    "warning_fg_color",
    "warning_color",
    "success_bg_color",
    "success_fg_color",
    "success_color",
)


def render_gtk(p: dict[str, object], version: str) -> str:
    colors = gtk_colors(p)
    colors.update(gtk_palette_scale(p))
    defines = "\n".join(
        f"@define-color {name} {value};" for name, value in colors.items()
    )

    if version == "3.0":
        return f"""/* {p["name"]} GTK3 adapter generated from palette.toml.
 * Requires the adw-gtk3 theme (pacman -S adw-gtk-theme); stock Adwaita
 * hardcodes its colors and ignores nearly all of these definitions. */
{defines}

/* Caret color has no named-color hook in either theme. */
entry,
textview,
textview text {{
  caret-color: {get(p, "cursor")};
}}
"""

    variables = "\n".join(
        f"  --{name.replace('_', '-')}: {colors[name]};" for name in GTK4_VARIABLES
    )
    return f"""/* {p["name"]} GTK4 adapter generated from palette.toml.
 * libadwaita 1.6+ reads the custom properties; @define-color is kept for
 * older libadwaita and for plain-GTK4 apps. */
{defines}

:root {{
{variables}
}}

entry,
textview,
textview text {{
  caret-color: {get(p, "cursor")};
}}
"""


def render_settings(p: dict[str, object]) -> str:
    """GTK's own settings file.

    Note this loses to org.gnome.desktop.interface whenever a settings portal
    is running (Wayland sessions normally have one), so themes/dconf.ini is
    the copy that actually decides the theme there; both are generated from
    the same palette so they cannot drift apart.
    """
    theme = "adw-gtk3-dark" if is_dark(p) else "adw-gtk3"
    return f"""[Settings]
gtk-application-prefer-dark-theme = {"true" if is_dark(p) else "false"}
gtk-theme-name = {theme}
gtk-icon-theme-name = {ICON_THEME}
gtk-cursor-theme-name = {CURSOR_THEME}
gtk-enable-animations = true
"""


def render_dconf(p: dict[str, object]) -> str:
    """Keys for `dconf load /org/gnome/desktop/interface/`."""
    theme = "adw-gtk3-dark" if is_dark(p) else "adw-gtk3"
    scheme = "prefer-dark" if is_dark(p) else "prefer-light"
    return f"""[/]
gtk-theme='{theme}'
color-scheme='{scheme}'
icon-theme='{ICON_THEME}'
cursor-theme='{CURSOR_THEME}'
"""


def render_wezterm(p: dict[str, object]) -> str:
    normal = ", ".join(f'"{ansi(p, "normal", name)}"' for name in ANSI_NAMES)
    bright = ", ".join(f'"{ansi(p, "bright", name)}"' for name in ANSI_NAMES)
    split = ansi(p, "bright", "black")
    return f"""-- Generated from palette.toml; WezTerm color adapter.
return {{
    foreground = "{get(p, "foreground")}",
    background = "{get(p, "background")}",
    cursor_bg = "{get(p, "cursor")}",
    cursor_fg = "{get(p, "cursor_text")}",
    selection_bg = "{get(p, "selection_background")}",
    selection_fg = "{get(p, "selection_foreground")}",
    ansi = {{ {normal} }},
    brights = {{ {bright} }},
    split = "{split}",
}}
"""


def render_niri(p: dict[str, object]) -> str:
    background = get(p, "background")
    active = get(p, "selection_background")
    inactive = ansi(p, "bright", "black")
    urgent = ansi(p, "bright", "red")
    return f"""// Generated from palette.toml; Niri layout adapter.
layout {{
  background-color "{background}"

  focus-ring {{
    active-color "{active}"
    inactive-color "{inactive}"
    urgent-color "{urgent}"
  }}

  border {{
    active-color "{active}"
    inactive-color "{inactive}"
    urgent-color "{urgent}"
  }}

  tab-indicator {{
    active-color "{active}"
    inactive-color "{inactive}"
    urgent-color "{urgent}"
  }}

  insert-hint {{
    color "{active}80"
  }}
}}
"""


def render_tmux(p: dict[str, object]) -> str:
    bg = get(p, "background")
    fg = get(p, "foreground")
    black = ansi(p, "normal", "black")
    white = ansi(p, "normal", "white")
    bright_yellow = ansi(p, "bright", "yellow")
    bright_red = ansi(p, "bright", "red")
    normal_red = ansi(p, "normal", "red")
    return f"""# Native tmux adapter generated from palette.toml.
set -g status-style "fg={white},bg={bg}"
set -g status-left-style "fg={fg},bg={bg}"
set -g status-right-style "fg={white},bg={bg}"
set-window-option -g window-status-style "fg={white},bg={bg}"
set-window-option -g window-status-current-style "fg={bg},bg={get(p, "selection_background")},bold"
set-window-option -g window-status-activity-style "fg={bright_yellow},bg={bg},underscore"
set-window-option -g window-status-bell-style "fg={ansi(p, "bright", "white")},bg={normal_red},bold"
set -g pane-border-style "fg={black}"
set -g pane-active-border-style "fg={get(p, "selection_background")}"
set -g message-style "fg={bg},bg={bright_yellow},bold"
set -g message-command-style "fg={bright_yellow},bg={bg},bold"
set -g mode-style "fg={bg},bg={bright_yellow},bold"
set -g clock-mode-colour "{ansi(p, "normal", "yellow")}"
"""


def render_delta(p: dict[str, object]) -> str:
    normal_black = ansi(p, "normal", "black")
    normal_red = ansi(p, "normal", "red")
    normal_green = ansi(p, "normal", "green")
    muted = ansi(p, "bright", "black")
    return f"""# Delta adapter generated from palette.toml.
[delta "gruvbox-dark"]
    dark = true
    syntax-theme = gruvbox-dark
    file-style = "{get(p, "foreground")}"
    file-decoration-style = "{ansi(p, "normal", "yellow")}"
    hunk-header-decoration-style = "{get(p, "selection_background")} box ul"
    hunk-header-file-style = "{ansi(p, "bright", "blue")}"
    hunk-header-line-number-style = "{ansi(p, "bright", "yellow")}"
    hunk-header-style = file line-number syntax
    line-numbers = true
    line-numbers-left-style = "{muted}"
    line-numbers-minus-style = "{normal_red}"
    line-numbers-plus-style = "{normal_green}"
    line-numbers-right-style = "{muted}"
    line-numbers-zero-style = "{ansi(p, "bright", "black")}"
    minus-emph-style = "normal {normal_red}"
    minus-style = "normal {normal_black}"
    plus-emph-style = "syntax {normal_green}"
    plus-style = "syntax {get(p, "background")}"
    zero-style = syntax
"""


def recolor_yazi(original: str, p: dict[str, object]) -> str:
    """Yazi's theme.toml mixes color values with static nerd-font glyphs and
    icon/extension lists. Rather than reconstructing the whole file from a
    template (risking mangling the glyphs), swap only the hex values that are
    already known to represent each palette role in this file, via a
    placeholder pass so a new value can never collide with an old one still
    waiting to be replaced."""
    n = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    roles = [
        ("#282828", get(p, "background")),
        ("#d5c4a1", get(p, "foreground")),
        ("#504945", get(p, "selection_background")),
        ("#3c3836", n["black"]),
        ("#665c54", NEUTRAL["bg3"]),
        ("#83a598", b["blue"]),
        ("#8ec07c", b["cyan"]),
        ("#fabd2f", b["yellow"]),
        ("#fb4934", b["red"]),
        ("#b8bb26", b["green"]),
        ("#d3869b", b["magenta"]),
        ("#928374", b["black"]),
    ]
    text = original
    placeholders = [f"\x00{i}\x00" for i in range(len(roles))]
    for (current_hex, _new_hex), token in zip(roles, placeholders):
        text = text.replace(current_hex, token)
    for (_current_hex, new_hex), token in zip(roles, placeholders):
        text = text.replace(token, new_hex)
    return text


def render_xresources(p: dict[str, object]) -> str:
    n = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    return f"""! Gruvbox Dark shared palette. Generated from palette.toml; do not edit by hand.
*.background:                      {get(p, "background")}
-*.background: [background_opacity]{get(p, "background")}
*.color0:                          {n["black"]}
*.color1:                          {n["red"]}
*.color2:                          {n["green"]}
*.color3:                          {n["yellow"]}
*.color4:                          {n["blue"]}
*.color5:                          {n["magenta"]}
*.color6:                          {n["cyan"]}
*.color7:                          {n["white"]}
*.color8:                          {b["black"]}
*.color9:                          {b["red"]}
*.color10:                         {b["green"]}
*.color11:                         {b["yellow"]}
*.color12:                         {b["blue"]}
*.color13:                         {b["magenta"]}
*.color14:                         {b["cyan"]}
*.color15:                         {b["white"]}
*.color16:                         {b["yellow"]}
*.color17:                         {n["yellow"]}
*.cursorColor:                     {get(p, "cursor")}
*.foreground:                      {get(p, "foreground")}
Xcursor.theme: Bibata-Modern-Ice
Xcursor.size: 30
"""


def render_gitu_style(p: dict[str, object]) -> str:
    n = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    return f"""section_header = {{ fg = "{n["yellow"]}" }}
file_header = {{ fg = "{b["magenta"]}" }}
hunk_header = {{ fg = "{b["blue"]}" }}

diff_highlight.tag_old = {{ fg = "{b["red"]}", mods = "BOLD" }}
diff_highlight.tag_new = {{ fg = "{b["green"]}", mods = "BOLD" }}
diff_highlight.unchanged_old = {{ mods = "DIM" }}
diff_highlight.unchanged_new = {{ mods = "DIM" }}
diff_highlight.changed_old = {{ fg = "{b["red"]}" }}
diff_highlight.changed_new = {{ fg = "{b["green"]}" }}

syntax_highlight.enabled = true
syntax_highlight.attribute = {{ fg = "{n["yellow"]}" }}
syntax_highlight.comment = {{ fg = "{b["black"]}" }}
syntax_highlight.constant_builtin = {{}}
syntax_highlight.constant = {{}}
syntax_highlight.constructor = {{}}
syntax_highlight.embedded = {{}}
syntax_highlight.function_builtin = {{ fg = "{b["cyan"]}" }}
syntax_highlight.function = {{ fg = "{b["blue"]}" }}
syntax_highlight.keyword = {{ fg = "{b["magenta"]}" }}
syntax_highlight.number = {{}}
syntax_highlight.module = {{ fg = "{b["cyan"]}" }}
syntax_highlight.property = {{}}
syntax_highlight.operator = {{}}
syntax_highlight.punctuation_bracket = {{}}
syntax_highlight.punctuation_delimiter = {{}}
syntax_highlight.string_special = {{ fg = "{b["yellow"]}" }}
syntax_highlight.string = {{ fg = "{n["yellow"]}" }}
syntax_highlight.tag = {{}}
syntax_highlight.type = {{ fg = "yellow" }}
syntax_highlight.type_builtin = {{ fg = "yellow" }}
syntax_highlight.variable_builtin = {{}}
syntax_highlight.variable_parameter = {{}}

cursor = {{ symbol = "▌", fg = "{n["yellow"]}" }}
selection_bar = {{ symbol = "▌", fg = "{get(p, "selection_background")}" }}
selection_line = {{ mods = "BOLD" }}
# You may want to set `selection_area.bg` to a nice background color.
# Looks horrible with regular terminal colors, so is therefore not set.
selection_area = {{}}

hash = {{ fg = "{b["yellow"]}" }}
branch = {{ fg = "{b["green"]}" }}
remote = {{ fg = "{b["red"]}" }}
tag = {{ fg = "{n["yellow"]}" }}

command = {{ fg = "{b["blue"]}", mods = "BOLD" }}
active_arg = {{ fg = "{b["red"]}", mods = "BOLD" }}
hotkey = {{ fg = "{b["magenta"]}" }}"""


def render_lazygit_theme(p: dict[str, object]) -> str:
    n = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    return f"""    # Border color of focused window
    activeBorderColor:
      - "{get(p, "selection_background")}"
      - bold
    # Border color of non-focused windows
    inactiveBorderColor:
      - "{b["black"]}"
    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - "{b["yellow"]}"
      - bold
    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - "{b["blue"]}"
    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - "{n["black"]}"
    # Background color of selected line when view doesn't have focus.
    inactiveViewSelectedLineBgColor:
      - "{n["black"]}"
    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - "{get(p, "background")}"
    # Background color of copied commit
    cherryPickedCommitBgColor:
      - "{b["blue"]}"
    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - "{get(p, "background")}"
    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - "{n["yellow"]}"
    # Color for file with unstaged changes
    unstagedChangesColor:
      - "{b["red"]}"
    # Default text color
    defaultFgColor:
      - "{get(p, "foreground")}\""""


def render_television_theme_overrides(p: dict[str, object]) -> str:
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    return f"""background = "{get(p, "background")}"
text_fg = "{get(p, "foreground")}"
selection_bg = "{get(p, "selection_background")}"
selection_fg = "{get(p, "background")}"
match_fg = "{b["yellow"]}"
border_fg = "{b["black"]}"
preview_title_fg = "{b["blue"]}\""""


def render_tmux_local_colours(p: dict[str, object]) -> str:
    n = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    bg = get(p, "background")
    fg = get(p, "foreground")
    sel = get(p, "selection_background")
    return f"""tmux_conf_theme_colour_1="{bg}"    # background
tmux_conf_theme_colour_2="{n["black"]}"    # panel
tmux_conf_theme_colour_3="{n["white"]}"    # muted text
tmux_conf_theme_colour_4="{sel}"    # active/focus blue
tmux_conf_theme_colour_5="{b["yellow"]}"    # focus gold
tmux_conf_theme_colour_6="{bg}"    # background
tmux_conf_theme_colour_7="{b["white"]}"    # bright text
tmux_conf_theme_colour_8="{bg}"    # background
tmux_conf_theme_colour_9="{b["yellow"]}"    # focus gold
tmux_conf_theme_colour_10="{b["magenta"]}"   # magenta
tmux_conf_theme_colour_11="{b["green"]}"   # green
tmux_conf_theme_colour_12="{n["white"]}"   # muted text
tmux_conf_theme_colour_13="{fg}"   # foreground
tmux_conf_theme_colour_14="{bg}"   # background
tmux_conf_theme_colour_15="{bg}"   # background
tmux_conf_theme_colour_16="{b["red"]}"   # red
tmux_conf_theme_colour_17="{b["white"]}"   # bright text"""


def render_tmux_local_thumbs(p: dict[str, object]) -> str:
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    return f"""set -g @thumbs-fg-color '{b["yellow"]}'
set -g @thumbs-bg-color '{get(p, "background")}'
set -g @thumbs-fg-color-match '{get(p, "foreground")}'
set -g @thumbs-bg-color-match '{get(p, "selection_background")}'"""


def render_fish_colors(p: dict[str, object]) -> str:
    """fish_color_*/fish_pager_color_* are fish's own theming variables —
    entirely separate from FZF_DEFAULT_OPTS, and unset elsewhere in this repo,
    so fish's native completion pager falls back to its stock (non-Gruvbox)
    colors. fish takes hex without a leading '#'."""

    def h(hex_value: str) -> str:
        return hex_value.lstrip("#")

    n = {name: ansi(p, "normal", name) for name in ANSI_NAMES}
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    fg = get(p, "foreground")
    bg = get(p, "background")
    sel = get(p, "selection_background")
    return f"""    # Syntax highlighting
    set -g fish_color_normal {h(fg)}
    set -g fish_color_command {h(n["blue"])}
    set -g fish_color_keyword {h(n["magenta"])}
    set -g fish_color_quote {h(n["green"])}
    set -g fish_color_redirection {h(n["cyan"])}
    set -g fish_color_end {h(n["yellow"])}
    set -g fish_color_error {h(b["red"])}
    set -g fish_color_param {h(fg)}
    set -g fish_color_option {h(n["cyan"])}
    set -g fish_color_comment {h(b["black"])}
    set -g fish_color_selection {h(fg)} --bold --background={h(sel)}
    set -g fish_color_search_match --background={h(sel)}
    set -g fish_color_operator {h(b["yellow"])}
    set -g fish_color_escape {h(b["magenta"])}
    set -g fish_color_autosuggestion {h(b["black"])}
    set -g fish_color_cwd {h(b["green"])}
    set -g fish_color_cwd_root {h(b["red"])}
    set -g fish_color_user {h(b["green"])}
    set -g fish_color_host {h(b["blue"])}
    set -g fish_color_cancel {h(b["red"])}

    # Tab-completion pager
    set -g fish_pager_color_progress {h(b["black"])}
    set -g fish_pager_color_prefix {h(b["yellow"])} --bold
    set -g fish_pager_color_completion {h(fg)}
    set -g fish_pager_color_description {h(b["black"])}
    set -g fish_pager_color_selected_background --background={h(sel)}
    set -g fish_pager_color_selected_prefix {h(bg)} --bold
    set -g fish_pager_color_selected_completion {h(bg)}
    set -g fish_pager_color_selected_description {h(bg)}"""


def render_fish_fzf(p: dict[str, object]) -> str:
    b = {name: ansi(p, "bright", name) for name in ANSI_NAMES}
    return f"""        set -l fzf_theme_opts "--color=fg:{get(p, "foreground")},bg:{get(p, "background")},hl:{b["yellow"]}
--color=fg+:{get(p, "background")},bg+:{get(p, "selection_background")},hl+:{get(p, "background")}
--color=info:{b["blue"]},prompt:{NEUTRAL["fg3"]},pointer:{b["blue"]}
--color=marker:{get(p, "selection_background")},spinner:{b["yellow"]},header:{b["black"]}\""""


def patch_markers(text: str, blocks: dict[str, str]) -> str:
    for name, body in blocks.items():
        start = f"# START_AUTOGENERATED_{name}"
        end = f"# END_AUTOGENERATED_{name}"
        # Capture whatever indentation precedes the end marker so it survives
        # the replacement (YAML/tmux blocks may nest it under indented keys).
        pattern = re.compile(
            re.escape(start) + r".*?([ \t]*)" + re.escape(end), re.DOTALL
        )
        match = pattern.search(text)
        if not match:
            fail(f"missing {name} marker block")
        indent = match.group(1)
        replacement = f"{start}\n{body}\n{indent}{end}"
        text, count = pattern.subn(lambda _m, r=replacement: r, text, count=1)
        if count != 1:
            fail(f"expected exactly one {name} marker block, found {count}")
    return text


# Files that mix hand-maintained settings with a palette-derived block,
# delimited by "# START_AUTOGENERATED_<NAME>" / "# END_AUTOGENERATED_<NAME>"
# markers already present in the file (same pattern kitty.conf uses for its
# tab-style block). Only the text between the markers is replaced.
MARKER_FILES = {
    REPO_ROOT / "config/fish/config.fish": lambda p: {
        "FZF_THEME": render_fish_fzf(p),
        "COLORS": render_fish_colors(p),
    },
    REPO_ROOT / "config/gitu/config.toml": lambda p: {"STYLE": render_gitu_style(p)},
    REPO_ROOT / "config/lazygit/config.yml": lambda p: {
        "THEME": render_lazygit_theme(p)
    },
    REPO_ROOT / "config/television/config.toml": lambda p: {
        "THEME_OVERRIDES": render_television_theme_overrides(p)
    },
    REPO_ROOT / "config/tmux/tmux.conf.local": lambda p: {
        "THEME_COLOURS": render_tmux_local_colours(p),
        "THEME_THUMBS": render_tmux_local_thumbs(p),
    },
}

# Files that are entirely palette-driven and can be regenerated wholesale.
FULL_FILE_TARGETS = {
    REPO_ROOT / "general/x/Xresources": render_xresources,
}

# Files patched by swapping known current hex values for their new palette
# role, rather than being reconstructed from a template (see recolor_yazi).
RECOLOR_FILES = {
    REPO_ROOT / "config/yazi/theme.toml": recolor_yazi,
}


GENERATORS = {
    "kitty.conf": render_kitty,
    "ghostty.conf": render_ghostty,
    "alacritty.toml": render_alacritty,
    "btop.theme": render_btop,
    "noctalia.json": render_noctalia,
    "dms.json": render_dms,
    "wezterm.lua": render_wezterm,
    "niri.kdl": render_niri,
    "tmux.conf": render_tmux,
    "delta.gitconfig": render_delta,
}


def generated_files(palette: dict[str, object]) -> dict[str, str]:
    files = {name: generator(palette) for name, generator in GENERATORS.items()}
    files["gtk-3.0.css"] = render_gtk(palette, "3.0")
    files["gtk-4.0.css"] = render_gtk(palette, "4.0")
    files["gtk-3.0-settings.ini"] = render_settings(palette)
    files["gtk-4.0-settings.ini"] = render_settings(palette)
    files["dconf.ini"] = render_dconf(palette)
    return files


def _srgb_channel(c: float) -> float:
    return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4


def relative_luminance(hex_color: str) -> float:
    r, g, b = (int(hex_color[i : i + 2], 16) / 255 for i in (1, 3, 5))
    r, g, b = (_srgb_channel(c) for c in (r, g, b))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast_ratio(hex_a: str, hex_b: str) -> float:
    la, lb = relative_luminance(hex_a), relative_luminance(hex_b)
    lighter, darker = max(la, lb), min(la, lb)
    return (lighter + 0.05) / (darker + 0.05)


# WCAG-style contrast floor for role pairs where "hard to see" is a real bug,
# not a style choice — this is what let the selection_background regression
# (1.7:1, invisible in fzf) ship silently. Deliberately narrow: ANSI text
# colors (e.g. a dim comment color) are often intentionally low-contrast, so
# only role pairs that must be visually distinct are checked.
CONTRAST_MIN = 3.0
CONTRAST_PAIRS = (
    ("selection_background", "background"),
    ("foreground", "background"),
)


def check_contrast(palette: dict[str, object]) -> None:
    for role_a, role_b in CONTRAST_PAIRS:
        ratio = contrast_ratio(get(palette, role_a), get(palette, role_b))
        if ratio < CONTRAST_MIN:
            print(
                f"generate.py: warning: {role_a} vs {role_b} contrast is "
                f"{ratio:.2f}:1 (below {CONTRAST_MIN:.0f}:1) — likely hard to see",
                file=sys.stderr,
            )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("palette", type=Path, help="canonical palette TOML file")
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="directory for generated adapters (defaults to the palette directory)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="check whether adapters are current without writing them",
    )
    args = parser.parse_args()

    try:
        palette = load_palette(args.palette)
        check_contrast(palette)
        output_dir = args.output_dir or args.palette.parent
        targets = {
            output_dir / name: content
            for name, content in generated_files(palette).items()
        }

        # FULL_FILE_TARGETS/MARKER_FILES live at fixed repo paths, independent
        # of --output-dir, which exists for testing generated_files() output
        # in isolation.
        if not args.output_dir:
            for path, generator in FULL_FILE_TARGETS.items():
                targets[path] = generator(palette)
            for path, blocks_fn in MARKER_FILES.items():
                if not path.exists():
                    fail(f"cannot patch {path}: file does not exist")
                targets[path] = patch_markers(path.read_text(), blocks_fn(palette))
            for path, recolor in RECOLOR_FILES.items():
                if not path.exists():
                    fail(f"cannot patch {path}: file does not exist")
                targets[path] = recolor(path.read_text(), palette)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"generate.py: error: {exc}", file=sys.stderr)
        return 2

    stale = []
    for destination, content in targets.items():
        if args.check:
            if not destination.exists() or destination.read_text() != content:
                stale.append(destination)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if not destination.exists() or destination.read_text() != content:
            destination.write_text(content)
            print(f"generated {destination}")

    if args.check and stale:
        for path in stale:
            print(f"stale {path}")
        return 1
    if args.check:
        print(f"{len(targets)} adapters are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
