#!/usr/bin/env bash

# Refresh completion files that are generated by installed CLI tools.
set -euo pipefail

REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BASH_COMPLETIONS_DIR="$REPO_DIR/bash/completions"
FISH_COMPLETIONS_DIR="$REPO_DIR/config/fish/completions"

generate_completion() {
  local command="$1"
  local destination="$2"
  local temporary
  shift 2

  if ! command -v "$command" >/dev/null 2>&1; then
    echo "Skipping $command completion: command is not installed." >&2
    return 0
  fi

  temporary=$(mktemp "${destination}.XXXXXX")
  if ! "$command" "$@" >"$temporary"; then
    rm -f "$temporary"
    echo "Failed to generate $destination." >&2
    return 1
  fi
  mv "$temporary" "$destination"
}

mkdir -p "$BASH_COMPLETIONS_DIR" "$FISH_COMPLETIONS_DIR"

generate_completion atuin "$FISH_COMPLETIONS_DIR/atuin.fish" gen-completions --shell fish
generate_completion bun "$FISH_COMPLETIONS_DIR/bun.fish" completions
generate_completion copilot "$FISH_COMPLETIONS_DIR/copilot.fish" completion fish
generate_completion gh "$FISH_COMPLETIONS_DIR/gh.fish" completion -s fish
generate_completion herdr "$FISH_COMPLETIONS_DIR/herdr.fish" completion fish
generate_completion niri "$FISH_COMPLETIONS_DIR/niri.fish" completions fish
generate_completion starship "$FISH_COMPLETIONS_DIR/starship.fish" completions fish
generate_completion tv "$FISH_COMPLETIONS_DIR/tv.fish" completions fish
generate_completion uv "$FISH_COMPLETIONS_DIR/uv.fish" generate-shell-completion fish

generate_completion atuin "$BASH_COMPLETIONS_DIR/atuin.bash" gen-completions --shell bash
generate_completion copilot "$BASH_COMPLETIONS_DIR/copilot.bash" completion bash
generate_completion gh "$BASH_COMPLETIONS_DIR/gh.bash" completion -s bash
generate_completion herdr "$BASH_COMPLETIONS_DIR/herdr.bash" completion bash
generate_completion niri "$BASH_COMPLETIONS_DIR/niri.bash" completions bash
generate_completion starship "$BASH_COMPLETIONS_DIR/starship.bash" completions bash
generate_completion tv "$BASH_COMPLETIONS_DIR/tv.bash" completions bash
generate_completion uv "$BASH_COMPLETIONS_DIR/uv.bash" generate-shell-completion bash
