# ==================
# ANIMATIONS
# ==================
animations {
    enabled = true

    animation = windowsIn, 1, 2.5, default
    animation = windowsOut, 1, 2.5, default
    animation = workspaces, 1, 4, default
    animation = windowsMove, 1, 3, default
    animation = fade, 1, 2.5, default
    animation = border, 1, 2.5, default
}
