# ==================
# STARTUP APPS
# ==================

# Session environment init
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target

# Non-critical maintenance
exec-once = trash-empty 30

# Start kanata
exec-once = sh -lc 'pgrep -af "kanata .*config.kbd" >/dev/null || kanata -c "$HOME/dotfiles/config/kanata/config.kbd"'
