# ==================
# INPUT CONFIG
# ==================
input {
  kb_layout = us,ru
  kb_options = grp:alt_shift_toggle
  numlock_by_default = true
  repeat_delay = 250
  repeat_rate = 35

  focus_on_close = 1

  touchpad {
    natural_scroll = true
    disable_while_typing = true
    scroll_factor = 0.3
  }
}

binds {
    scroll_event_delay = 0
}

env = XCURSOR_THEME, sweet-cursors
env = XCURSOR_SIZE, 18

cursor {
  hotspot_padding = 1
}
