# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # configure pyenv
    if [ -d $HOME/.pyenv ]; then
        # avoid re-initialisation
        if [ -z "${PYENV_ROOT+x}" ]; then
            # init pyenv
            export PYENV_ROOT=$HOME/.pyenv
            export PATH=$HOME/.pyenv/bin:$PATH
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
        fi
    fi

    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        source "$HOME/.bashrc"
    fi
fi
