alias -- -="cd -"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# yazi alias
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

# ruff alias
function ruff_format() {
    local file_to_format=$1

    # Sort imports and fix issues
    ruff check --select I --fix $file_to_format

    # Format the file
    ruff format $file_to_format
}

# aichat alias
function aichat() {
    local DEEPSEEK_API_KEY=$(copy_password.sh deepseek)
    local GEMINI_API_KEY=$(copy_password.sh gemini)
    env DEEPSEEK_API_KEY="$DEEPSEEK_API_KEY" GEMINI_API_KEY="$GEMINI_API_KEY" aichat "$@"
}

# install fonts
function install_fonts() {
    local source_dir="$1"
    local prefix="$2"
    local subdirectory="$3"

    # Check if source directory is provided
    if [ -z "$source_dir" ]; then
        echo "Error: Please provide the source directory as an argument."
        return 1
    fi

    # Determine the base font directory based on the OS
    if [ "$(uname)" = "Darwin" ]; then
        # macOS
        base_font_dir="$HOME/Library/Fonts"
    else
        # Linux
        base_font_dir="$HOME/.local/share/fonts"
    fi

    # Set the target font directory
    if [ -n "$subdirectory" ]; then
        font_dir="$base_font_dir/$subdirectory"
    else
        font_dir="$base_font_dir"
    fi

    # Create the target directory if it doesn't exist
    mkdir -p "$font_dir"

    # Copy fonts to the target directory
    echo "Copying fonts from $source_dir to $font_dir..."
    if [ -n "$prefix" ]; then
        find "$source_dir" \( -name "$prefix*.[ot]tf" -or -name "$prefix*.pcf.gz" \) -type f -print0 | xargs -0 -n1 -I % cp "%" "$font_dir/"
    else
        find "$source_dir" \( -name "*.[ot]tf" -or -name "*.pcf.gz" \) -type f -print0 | xargs -0 -n1 -I % cp "%" "$font_dir/"
    fi

    # Reset font cache on Linux
    if command -v fc-cache >/dev/null 2>&1; then
        echo "Resetting font cache, this may take a moment..."
        fc-cache -f "$font_dir"
    fi

    echo "Fonts installed to $font_dir"
}

# If inside a kitty terminal, add aliases for kitty's icat, ssh, diff, and hg
if [[ -n $KITTY_PID ]]; then
  alias icat="kitten icat"
  alias ssh="kitty +kitten ssh"
  alias realssh="/usr/bin/ssh"
  alias diff="kitten diff"
  alias hg="kitten hyperlinked-grep"
fi
