# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# reuse ssh between logins
type keychain >&/dev/null \
    && keychain --agents ssh $HOME/.ssh/id_rsa
    && keychain --agents gpg C1E56A68AE1A8A7D92B88B2AB2FE6C77CC4B6C4A

# configure pyenv
if [ -d $HOME/.pyenv ]; then
    # init pyenv
    export PYENV_ROOT=$HOME/.pyenv
    export PATH=$HOME/.pyenv/bin:$PATH
fi

# include .bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi

eval "$(pyenv init --path)"