;;; autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "config-ai" "config-ai.el" (0 0 0 0))
;;; Generated autoloads from config-ai.el

(autoload 'aam/ai-setup "config-ai")

;;;***

;;;### (autoloads nil "config-bibtex" "config-bibtex.el" (0 0 0 0))
;;; Generated autoloads from config-bibtex.el

(autoload 'aam/bibtex-setup "config-bibtex")

(register-definition-prefixes "config-bibtex" '("aam/bibtex-generate-autokey"))

;;;***

;;;### (autoloads nil "config-common" "config-common.el" (0 0 0 0))
;;; Generated autoloads from config-common.el

(autoload 'aam/common-setup "config-common")

;;;***

;;;### (autoloads nil "config-lsp" "config-lsp.el" (0 0 0 0))
;;; Generated autoloads from config-lsp.el

(autoload 'aam/lsp-setup "config-lsp")

;;;***

;;;### (autoloads nil "config-mail" "config-mail.el" (0 0 0 0))
;;; Generated autoloads from config-mail.el

(autoload 'aam/mail-setup "config-mail")

;;;***

;;;### (autoloads nil "config-org" "config-org.el" (0 0 0 0))
;;; Generated autoloads from config-org.el

(autoload 'aam/org-setup "config-org")

(autoload 'aam-org-weekly-journal-file "config-org")

(autoload 'aam-org-weekly-journal-find-location "config-org")

;;;***

;;;### (autoloads nil "config-python" "config-python.el" (0 0 0 0))
;;; Generated autoloads from config-python.el

(autoload 'aam/python-setup "config-python")

;;;***

;;;### (autoloads nil "config-secure" "config-secure.el" (0 0
;;;;;;  0 0))
;;; Generated autoloads from config-secure.el

(autoload 'aam/secure-setup "config-secure")

;;;***

;;;### (autoloads nil "config-tex" "config-tex.el" (0 0 0 0))
;;; Generated autoloads from config-tex.el

(autoload 'aam/tex-setup "config-tex")

;;;***

;;; End of scraped data

(provide 'autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; autoloads.el ends here
