export ALTERNATE_EDITOR=nvim
export TERMINAL=kitty
export FILE_MANAGER=thunar
export BROWSER=microsoft-edge-stable
export EDITOR=emacsclient-visual.sh
export VISUAL=emacsclient-visual.sh

eval `gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh`
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_PID

[ -e $HOME/.Xmodmap ] && exec xmodmap $HOME/.Xmodmap
exec xsetroot -cursor_name left_ptr
exec xset s off
exec xset b off
